site_name: Disnake Guide
site_description: A guide for disnake.
site_url: https://disnakedev.github.io/guide

theme:
    name: material
    features:
        - navigation.instant
        - navigation.expand
    language: en
    palette:
        - media: "(prefers-color-scheme: light)"
          scheme: default
          toggle: 
            icon: material/weather-sunny
            name: Light Mode
        - media: "(prefers-color-scheme: dark)"
          scheme: slate
          toggle:
            icon: material/weather-night
            name: Dark Mode

repo_name: DisnakeDev/guide
repo_url: https://github.com/DisnakeDev/guide

plugins:
    - search

markdown_extensions:
    - tables
    - admonition
    - pymdownx.highlight
    - pymdownx.inlinehilite
    - pymdownx.superfences
    - pymdownx.snippets
    - pymdownx.details
    - pymdownx.superfences
    - pymdownx.emoji:
        emoji_index: !!python/name:materialx.emoji.twemoji
        emoji_generator: !!python/name:materialx.emoji.to_svg

nav:
    - index.md
    - Basics:
        - basics/index.md
        - basics/making-your-application.md
        - basics/coding-your-bot.md
    - Commands:
        - commands/index.md
        - commands/basic.md

extra_css:
    - stylesheets/extra.css
