site_name: Disnake Guide
site_description: A guide for disnake.
site_url: https://guide.disnake.dev/

theme:
    name: material
    logo: disnake.png
    favicon: disnake.png
    features:
        - navigation.instant
        - navigation.expand
    language: en
    palette:
        - media: "(prefers-color-scheme: light)"
          scheme: light
          toggle: 
            icon: material/weather-sunny
            name: Light Mode
        - media: "(prefers-color-scheme: dark)"
          scheme: dark
          toggle:
            icon: material/weather-night
            name: Dark Mode

repo_name: DisnakeDev/disnake
repo_url: https://github.com/DisnakeDev/disnake

plugins:
    - search

markdown_extensions:
    - tables
    - admonition
    - attr_list
    - pymdownx.highlight
    - pymdownx.inlinehilite
    - pymdownx.superfences
    - pymdownx.snippets
    - pymdownx.details
    - pymdownx.superfences
    - markdown_link_attr_modifier:
        new_tab: external_only
    - pymdownx.emoji:
        emoji_index: !!python/name:materialx.emoji.twemoji
        emoji_generator: !!python/name:materialx.emoji.to_svg

nav:
    - index.md
    - Guide:
        - guide/making-your-application.md
        - guide/coding-your-bot.md
    - Command Samples:
        - commands/index.md
        - commands/basic.md
    - good-practices.md

extra_css:
    - stylesheets/extra.css
