name: Build docs

on: push

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch_depth: 0
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          pip install mkdocs-material
          pip install -r requirements.txt
      - name: Run pre-commit
        uses: pre-commit/action@v2.0.3
      - name: Deploy docs
        run: mkdocs gh-deploy --force
